/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookRouteImport } from './routes/book'
import { Route as DiningRouteImport } from './routes/dining'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as StayIndexRouteImport } from './routes/stay.index'
import { Route as StaySlugRouteImport } from './routes/stay.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const DiningRoute = DiningRouteImport.update({
  id: '/dining',
  path: '/dining',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StayIndexRoute = StayIndexRouteImport.update({
  id: '/stay/',
  path: '/stay/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaySlugRoute = StaySlugRouteImport.update({
  id: '/stay/$slug',
  path: '/stay/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/dining': typeof DiningRoute
  '/experience': typeof ExperienceRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/stay/$slug': typeof StaySlugRoute
  '/journal/': typeof JournalIndexRoute
  '/stay/': typeof StayIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/dining': typeof DiningRoute
  '/experience': typeof ExperienceRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/stay/$slug': typeof StaySlugRoute
  '/journal': typeof JournalIndexRoute
  '/stay': typeof StayIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/dining': typeof DiningRoute
  '/experience': typeof ExperienceRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/stay/$slug': typeof StaySlugRoute
  '/journal/': typeof JournalIndexRoute
  '/stay/': typeof StayIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/dining'
    | '/experience'
    | '/journal/$slug'
    | '/stay/$slug'
    | '/journal/'
    | '/stay/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/dining'
    | '/experience'
    | '/journal/$slug'
    | '/stay/$slug'
    | '/journal'
    | '/stay'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/dining'
    | '/experience'
    | '/journal/$slug'
    | '/stay/$slug'
    | '/journal/'
    | '/stay/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRoute
  DiningRoute: typeof DiningRoute
  ExperienceRoute: typeof ExperienceRoute
  JournalSlugRoute: typeof JournalSlugRoute
  StaySlugRoute: typeof StaySlugRoute
  JournalIndexRoute: typeof JournalIndexRoute
  StayIndexRoute: typeof StayIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dining': {
      id: '/dining'
      path: '/dining'
      fullPath: '/dining'
      preLoaderRoute: typeof DiningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stay/': {
      id: '/stay/'
      path: '/stay'
      fullPath: '/stay/'
      preLoaderRoute: typeof StayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stay/$slug': {
      id: '/stay/$slug'
      path: '/stay/$slug'
      fullPath: '/stay/$slug'
      preLoaderRoute: typeof StaySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRoute,
  DiningRoute: DiningRoute,
  ExperienceRoute: ExperienceRoute,
  JournalSlugRoute: JournalSlugRoute,
  StaySlugRoute: StaySlugRoute,
  JournalIndexRoute: JournalIndexRoute,
  StayIndexRoute: StayIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
